name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    if: github.repository_owner == 'KarunAtreya'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    # Build Vue frontend
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Vue dependencies
      working-directory: ./vue
      run: yarn install
    - name: Build Vue dependencies
      working-directory: ./vue
      run: yarn build
    - name: Install Django dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get install -y libsasl2-dev python3-dev libldap2-dev libssl-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python3 manage.py collectstatic --noinput
        python3 manage.py collectstatic_js_reverse
    - name: e2e tests
      working-directory: ./tests
      env:
        APP_URL: http://localhost/
      run: |
        npm i -D @playwright/test
        npm i -D playwright
        npx playwright install
        npm i -D @cucumber/cucumber @cucumber/pretty-formatter
        npm run test:e2e tests/e2e/features



